name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        # MongoDB Version
        mongoDBVersion: default# default is 3.6
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
